add_subdirectory(./algorithms)
add_subdirectory(./image)
add_subdirectory(./visControls)
add_subdirectory(./visPrimitives)
add_subdirectory(./screenLayer)
add_subdirectory(./events)
add_subdirectory(./eventManager)
add_subdirectory(./renderManager)
add_subdirectory(./facade)
set(SOURCES "${SOURCES}" PARENT_SCOPE)
set(INCLUDES "${INCLUDES}" PARENT_SCOPE)
set(LINKS "${LINKS}" PARENT_SCOPE)
