cmake_minimum_required(VERSION 3.10)
project(bDrive VERSION 1.0 LANGUAGES CXX)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/release)
include(CTest)
add_subdirectory(./code)
include_directories(${INCLUDES})
add_library(bdrive SHARED ${SOURCES})
target_link_libraries(bdrive ${LINKS})
add_test(NAME haffmanTests COMMAND haffmanTests)
